const products = [
    {
        id: 0,
        name: "Blue Moon",
        price: 1300,
        instock: 8,
        description: "2022 diary with our famous cat Luna, seeing the moon reflected in the water",
        imgScr: "./img/merchan/agendas/blueagendas.jpg",
    },
    {
        id: 1,
        name: "Ballons",
        price: 1300,
        instock: 8,
        description: "2022 diary with Luna having a balloon adventure",
        imgScr: "./img/merchan/agendas/pinkagendas.jpg",
    },
    {
        id: 2,
        name: "Bitacoras",
        price: 750,
        instock: 5,
        description: "A story to play, read and color",
        imgScr: "./img/merchan/books/bitacoras-front.jpg",
    },
    {
        id: 3,
        name: "El escritor de exitos",
        price: 500,
        instock: 5,
        description: "Compilation of my adventures with art and drawing",
        imgScr: "./img/merchan/books/escritor-front.jpg",
    },
    {
        id: 4,
        name: "Garabatos",
        price: 900,
        instock: 5,
        description: "Compilation of stories, characters, jokes and reflections",
        imgScr: "./img/merchan/books/garabatos-front.jpg",
    },
    {
        id: 5,
        name: "Garabatos 2",
        price: 900,
        instock: 5,
        description: "Second installment of our successful book, with new stories and characters",
        imgScr: "./img/merchan/books/garabatos2-front.jpg",
    },
    {
        id: 6,
        name: "Luna",
        price: 800,
        instock: 5,
        description: "My story with an amazing kitty named Luna",
        imgScr: "./img/merchan/books/luna-front.jpg",
    },
    {
        id: 7,
        name: "Supercat Luna",
        price: 700,
        instock: 7,
        description: "Logbook with Luna dressing like a superhero",
        imgScr: "./img/merchan/logbooks/logbookfront-01.png",
    },
    {
        id: 8,
        name: "Luna with dark background",
        price: 700,
        instock: 7,
        description: "Logbook with Luna making funny faces",
        imgScr: "./img/merchan/logbooks/logbookfront-02.png",
    },
    {
        id: 9,
        name: "Luna with dark background",
        price: 1200,
        instock: 10,
        description: "Mug with Luna making funny faces",
        imgScr: "./img/merchan/mugs/mug-01.jpg",
    },
    {
        id: 10,
        name: "101 Lunas",
        price: 1200,
        instock: 10,
        description: "The one hundred and one Lunas mug",
        imgScr: "./img/merchan/mugs/mug-02.jpg",
    },
    {
        id: 11,
        name: "Dreaming in the clouds",
        price: 1200,
        instock: 10,
        description: "Mug with Luna dreaming in the clouds",
        imgScr: "./img/merchan/mugs/mug-03.jpg",
    },
    {
        id: 12,
        name: "Curious Luna",
        price: 1200,
        instock: 10,
        description: "Mug with our favourite kitten wondering about the misteries of the universe",
        imgScr: "./img/merchan/mugs/mug-04.jpg",
    },
    ]


